// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUniCDWJqmMjIUzTtTAbyRChaginDnk4A',
    appId: '1:644047843601:web:03aa2a702915daff509cb0',
    messagingSenderId: '644047843601',
    projectId: 'gps-tracker-101',
    authDomain: 'gps-tracker-101.firebaseapp.com',
    storageBucket: 'gps-tracker-101.firebasestorage.app',
    measurementId: 'G-V8P2YC0R51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA48Bo_gRhviiQ_k-c44HbTBk2XLCRcq2U',
    appId: '1:644047843601:android:dfa90e54ee0f9626509cb0',
    messagingSenderId: '644047843601',
    projectId: 'gps-tracker-101',
    storageBucket: 'gps-tracker-101.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS5_W3KfnJoTGbZpjyW9uLw4digwq9L7Q',
    appId: '1:644047843601:ios:f071eed0d9c339ff509cb0',
    messagingSenderId: '644047843601',
    projectId: 'gps-tracker-101',
    storageBucket: 'gps-tracker-101.firebasestorage.app',
    iosBundleId: 'com.example.vehicleTrackingSystem',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS5_W3KfnJoTGbZpjyW9uLw4digwq9L7Q',
    appId: '1:644047843601:ios:f071eed0d9c339ff509cb0',
    messagingSenderId: '644047843601',
    projectId: 'gps-tracker-101',
    storageBucket: 'gps-tracker-101.firebasestorage.app',
    iosBundleId: 'com.example.vehicleTrackingSystem',
  );
}
